development:
  clients:
    default:
      database: comentarios_ms_development
      hosts:
        - "comentarios_db:27018"

test:
  clients:
    default:
      database: comentarios_ms_test
      hosts:
        - "comentarios_db:27018"

production:
  clients:
    default:
      database: comentarios_ms_production
      hosts:
        - "comentarios_db:27018"
